### ISSUE TITLE
Add Release

### ISSUE THREAD

**Issue by j-tag** [tonyaxo/yii2-recaptcha#1]
Please consider to add a release tag so we can use this project without composer conflicts in minimum-stability.

At this time if I add this project to my composer, I will get this error:
`- The requested package tonyaxo/yii2-recaptcha * is satisfiable by tonyaxo/yii2-recaptcha[dev-master] but these conflict with your requirements or minimum-stability.`

**Comment by tonyaxo** [comment]
done
